# Generated by Django 2.2.2 on 2019-06-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xq_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologys',
            name='add_time',
        ),
    ]
