# Generated by Django 2.2.2 on 2019-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xq_type', '0002_remove_technologys_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologys',
            name='level',
            field=models.IntegerField(default=1, verbose_name='等级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technologys',
            name='percentage',
            field=models.IntegerField(default=1, verbose_name='未知'),
            preserve_default=False,
        ),
    ]
