# Generated by Django 2.2.2 on 2019-06-11 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage', models.CharField(max_length=30, verbose_name='学院')),
                ('gender', models.CharField(choices=[('male', '男'), ('famale', '女')], default='男', max_length=6)),
                ('minzu', models.CharField(max_length=30, verbose_name='民族')),
                ('jiguan', models.CharField(max_length=30, verbose_name='籍贯')),
                ('major', models.CharField(max_length=30, verbose_name='专业')),
            ],
            options={
                'verbose_name': '统计分析',
                'verbose_name_plural': '统计分析',
            },
        ),
        migrations.CreateModel(
            name='AssistTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('job_number', models.CharField(max_length=50, verbose_name='工号')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('college', models.CharField(default='', max_length=20, verbose_name='学院')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('assist_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='帮扶地点')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '帮扶老师信息',
                'verbose_name_plural': '帮扶老师信息',
            },
        ),
        migrations.CreateModel(
            name='Associate_native_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('jiguan', models.CharField(max_length=30, verbose_name='籍贯')),
            ],
            options={
                'verbose_name': '关联分析-籍贯',
                'verbose_name_plural': '关联分析-籍贯',
            },
        ),
        migrations.CreateModel(
            name='Associateaward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
            ],
            options={
                'verbose_name': '关联分析-奖励',
                'verbose_name_plural': '关联分析-奖励',
            },
        ),
        migrations.CreateModel(
            name='AssociateBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('number', models.IntegerField(verbose_name='借阅次数')),
            ],
            options={
                'verbose_name': '关联分析-借阅次数',
                'verbose_name_plural': '关联分析-借阅次数',
            },
        ),
        migrations.CreateModel(
            name='AssociateCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30, verbose_name='课程号')),
                ('course_name', models.CharField(max_length=30, verbose_name='成绩')),
            ],
            options={
                'verbose_name': '关联分析-课程成绩',
                'verbose_name_plural': '关联分析-课程成绩',
            },
        ),
        migrations.CreateModel(
            name='AssociateCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('course_id', models.CharField(max_length=30, verbose_name='课程号')),
                ('grade', models.IntegerField(verbose_name='成绩')),
            ],
            options={
                'verbose_name': '关联分析-课程成绩',
                'verbose_name_plural': '关联分析-课程成绩',
            },
        ),
        migrations.CreateModel(
            name='AssociateGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('gender', models.CharField(choices=[('male', '男'), ('famale', '女')], default='男', max_length=6)),
                ('collage', models.CharField(max_length=30, verbose_name='学院')),
            ],
            options={
                'verbose_name': '关联分析-学院男女',
                'verbose_name_plural': '关联分析-学院男女',
            },
        ),
        migrations.CreateModel(
            name='AssociateGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('grade', models.IntegerField(verbose_name='成绩')),
            ],
            options={
                'verbose_name': '关联分析-成绩',
                'verbose_name_plural': '关联分析-成绩',
            },
        ),
        migrations.CreateModel(
            name='BorrowAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='学号')),
                ('frequency', models.IntegerField(verbose_name='科目数')),
                ('number', models.IntegerField(verbose_name='借阅次数')),
            ],
            options={
                'verbose_name': '关联分析-借阅结果',
                'verbose_name_plural': '关联分析-借阅结果',
            },
        ),
        migrations.CreateModel(
            name='GraduateCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('st_id', models.CharField(max_length=50, verbose_name='学号')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('myclass', models.CharField(max_length=10, verbose_name='班级')),
                ('sum_credit', models.FloatField(default=0, verbose_name='总学分')),
                ('finish_credit', models.FloatField(default=0, verbose_name='已修学分')),
                ('need_credit', models.FloatField(default=0, verbose_name='还需学分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '毕业审核',
                'verbose_name_plural': '毕业审核',
            },
        ),
        migrations.CreateModel(
            name='StudenCreditManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('st_id', models.CharField(max_length=50, verbose_name='学号')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('myclass', models.CharField(max_length=10, verbose_name='班级')),
                ('sum_credit', models.FloatField(default=0, verbose_name='总学分')),
                ('finish_credit', models.FloatField(default=0, verbose_name='已修学分')),
                ('need_credit', models.FloatField(default=0, verbose_name='还需学分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学分管理',
                'verbose_name_plural': '学分管理',
            },
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('st_id', models.CharField(max_length=50, verbose_name='学号')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('myclass', models.CharField(max_length=10, verbose_name='班级')),
                ('warm_leve', models.CharField(default='', max_length=20, verbose_name='预警等级')),
                ('assist_teacher', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='帮扶老师')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmin.AssistTeacher', verbose_name='工号')),
            ],
            options={
                'verbose_name': '帮扶计划',
                'verbose_name_plural': '帮扶计划',
            },
        ),
    ]
