# Generated by Django 2.2.2 on 2019-06-11 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=30, unique=True, verbose_name='课程代码')),
                ('title', models.CharField(max_length=50, verbose_name='课程名')),
                ('credit', models.FloatField(default=0.0, verbose_name='学分')),
                ('period', models.CharField(max_length=10, verbose_name='学时')),
                ('semester', models.CharField(max_length=10, verbose_name='开课学期')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('college', models.CharField(max_length=50, verbose_name='学院')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '所有课程',
                'verbose_name_plural': '所有课程',
            },
        ),
        migrations.CreateModel(
            name='LearnWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('year', models.CharField(max_length=20, verbose_name='学年')),
                ('semester', models.CharField(max_length=10, verbose_name='学期')),
                ('college', models.CharField(default='计算机学院', max_length=20, verbose_name='学院')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('myclass', models.CharField(max_length=10, verbose_name='班级')),
                ('is_send', models.IntegerField(default=0, verbose_name='发送短信')),
                ('level', models.CharField(choices=[('退学预警', '退学预警'), ('降级预警', '降级预警'), ('跟班修读', '跟班修读'), ('警示预警', '警示预警')], default='正常', max_length=10, verbose_name='预警等级')),
                ('warm_creadit', models.FloatField(default=0, verbose_name='挂科学分')),
                ('message', models.TextField(default='正常', verbose_name='预警消息')),
                ('assit_teacher', models.CharField(default='', max_length=30, verbose_name='帮扶老师')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '预警消息',
                'verbose_name_plural': '预警消息',
            },
        ),
        migrations.CreateModel(
            name='MajorSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50, verbose_name='学院')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('c_type', models.CharField(max_length=100, verbose_name='课程性质')),
                ('sum_credit', models.FloatField(default=0, verbose_name='总学分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学分要求',
                'verbose_name_plural': '学分要求',
                'ordering': ['id'],
                'get_latest_by': 'add_time',
            },
        ),
        migrations.CreateModel(
            name='StCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('accomplish', models.FloatField(default=0, verbose_name='已修学分')),
                ('unfinshed', models.FloatField(default=0, verbose_name='未修学分')),
                ('c_type', models.CharField(max_length=100, verbose_name='课程性质')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生学分管理',
                'verbose_name_plural': '学生学分管理',
            },
        ),
        migrations.CreateModel(
            name='WarnRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='北方民族大学', max_length=50, verbose_name='学校名称')),
                ('level', models.CharField(max_length=30, verbose_name='预警等级')),
                ('sum_credit', models.FloatField(default=0, verbose_name='一学年所需学分')),
                ('all_credit', models.FloatField(default=0, verbose_name='在校期间所需学分')),
                ('truant', models.IntegerField(blank=True, null=True, verbose_name='旷课节数')),
                ('item', models.TextField(blank=True, null=True, verbose_name='其他')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '预警等级',
                'verbose_name_plural': '预警等级',
            },
        ),
        migrations.CreateModel(
            name='StGgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50, verbose_name='学号')),
                ('title', models.CharField(max_length=50, verbose_name='课程名')),
                ('credit', models.FloatField(default=0.0, verbose_name='学分')),
                ('grade', models.FloatField(default=0.0, verbose_name='成绩')),
                ('year', models.CharField(max_length=20, verbose_name='学年')),
                ('semester', models.CharField(max_length=10, verbose_name='学期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('c_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courese.MajorSystem', verbose_name='课程性质')),
            ],
            options={
                'verbose_name': '历年成绩',
                'verbose_name_plural': '历年成绩',
            },
        ),
    ]
