# Generated by Django 2.2.2 on 2019-06-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnwarning',
            name='st_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='users.MyMessage', verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='coursetable',
            name='c_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courese.MajorSystem', verbose_name='课程性质'),
        ),
    ]
