# Generated by Django 2.2.2 on 2019-06-11 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xq_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='项目名')),
                ('url', models.URLField(default='', verbose_name='地址')),
                ('click_times', models.IntegerField(default=0, verbose_name='点击次数')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xq_type.Types', verbose_name='标签')),
            ],
            options={
                'verbose_name': '最热开源项目',
                'verbose_name_plural': '最热开源项目',
            },
        ),
        migrations.CreateModel(
            name='HotJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='职位名')),
                ('salary', models.CharField(default='', max_length=30, verbose_name='薪资')),
                ('url', models.URLField(default='', verbose_name='链接地址')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('click_times', models.PositiveIntegerField(default=0, verbose_name='点击次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xq_type.Types', verbose_name='标签')),
            ],
            options={
                'verbose_name': '热门职位',
                'verbose_name_plural': '热门职位',
                'ordering': ['id'],
                'get_latest_by': 'add_time',
            },
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(default='', max_length=50, verbose_name='学号')),
                ('title', models.CharField(default='', max_length=100, verbose_name='书名')),
                ('borrow_times', models.IntegerField(default=0, verbose_name='借阅次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xq_type.Types', verbose_name='标签')),
            ],
            options={
                'verbose_name': '图书馆借书',
                'verbose_name_plural': '图书馆借书',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='大赛名')),
                ('url', models.URLField(default='', verbose_name='链接地址')),
                ('content', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('image', models.ImageField(default='banner/default.png', upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xq_type.Types', verbose_name='标签')),
            ],
            options={
                'verbose_name': '大赛信息',
                'verbose_name_plural': '大赛信息',
            },
        ),
        migrations.CreateModel(
            name='Artcle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='资讯名')),
                ('url', models.URLField(default='', verbose_name='链接地址')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('click_times', models.IntegerField(default=0, verbose_name='点击次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xq_type.Types', verbose_name='标签')),
            ],
            options={
                'verbose_name': '热门资讯',
                'verbose_name_plural': '热门资讯',
                'ordering': ['id'],
                'get_latest_by': 'add_time',
            },
        ),
    ]
